import fs from 'fs';
import path from 'path';
import prettier from 'prettier';
import { AssetGenConfig } from '../utils/config.js';
import { scanAssets, relativeImportPath } from '../utils/file.js';
import { toVariableName, checkDuplicates } from '../utils/naming.js';
import { renderTemplate } from '../templates/asset.template.js';
import { getMessages } from '../utils/i18n.js';

export async function generateAssets(config: AssetGenConfig): Promise<void> {
  const { input, output, extensions, naming, language } = config;
  const msg = getMessages(language);

  const files = await scanAssets(input, extensions);

  const basenames = files.map((f) => path.basename(f));
  checkDuplicates(basenames, naming, msg);

  const entries = files.map((file) => ({
    variableName: toVariableName(path.basename(file), naming),
    importPath: relativeImportPath(output, input, file),
  }));

  const raw = renderTemplate(entries);
  const formatted = await prettier.format(raw, { parser: 'typescript' });

  const outputPath = path.resolve(process.cwd(), output);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, formatted, 'utf-8');
}

export async function generateDeclarations(config: AssetGenConfig): Promise<string> {
  const { output, extensions } = config;

  const declarations = extensions
    .map(
      (ext) =>
        `declare module '*.${ext}' {\n  const src: string;\n  export default src;\n}`
    )
    .join('\n\n');

  const content = `// Generated by asset-gen — do not edit manually\n\n${declarations}\n`;

  const outputDir = path.dirname(path.resolve(process.cwd(), output));
  const declPath = path.join(outputDir, 'asset-gen.d.ts');
  fs.writeFileSync(declPath, content, 'utf-8');

  return path.relative(process.cwd(), declPath);
}
